"""Action Proposal, Policy Decisions, and Human Approval Schemas."""

import hashlib
import json
from decimal import Decimal
from enum import Enum
from datetime import datetime, timezone
from typing import Optional, Any, Literal
from pydantic import BaseModel, Field, field_serializer
from packages.schemas.trust import TrustLevel
from packages.schemas.tools import RiskTier


class DecisionType(str, Enum):
    EXECUTE = "EXECUTE"
    REVIEW = "REVIEW"
    RETRY = "RETRY"
    REJECT = "REJECT"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_EVIDENCE_REQUESTED = "MORE_EVIDENCE_REQUESTED"
    INVALIDATED = "INVALIDATED"


class ActionProposal(BaseModel):
    """Structured proposal generated by an agent reasoning step.
    
    The agent CANNOT directly execute this action. It is strictly evaluated
    by the deterministic policy layer.
    """
    proposal_id: str
    workflow_id: str
    run_id: str
    organization_id: str
    agent_id: str
    action: str  # e.g., 'issue_refund', 'update_crm', 'send_email'
    target: str  # e.g., 'txn_5521', 'cus_9281'
    parameters: dict[str, Any]
    reason: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_ids: list[str] = Field(default_factory=list)
    state_version: int = 1
    observed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime
    trust_level: TrustLevel = TrustLevel.CUSTOMER_EMAIL
    risk_tier: RiskTier = RiskTier.TIER_3_FINANCIAL_DESTRUCTIVE

    def compute_action_hash(self) -> str:
        """Deterministic cryptographic SHA-256 hash of the exact proposal parameters.
        
        Guarantees that human approval binds only to THIS EXACT action proposal
        and cannot be swapped or applied to changed parameters.
        """
        canonical_dict = {
            "action": self.action,
            "target": self.target,
            "parameters": self.parameters,
            "state_version": self.state_version,
            "organization_id": self.organization_id,
        }
        # Serialize to deterministic JSON with sorted keys
        serialized = json.dumps(canonical_dict, sort_keys=True, default=str)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def generate_idempotency_key(self) -> str:
        """Canonical idempotency key for preventing duplicate consequential executions.
        
        Format: wf_<workflow_id>:<action>:<target>:<hash_prefix>
        """
        action_hash = self.compute_action_hash()
        return f"wf_{self.workflow_id}:{self.action}:{self.target}:{action_hash[:16]}"


class RefundProposal(BaseModel):
    """Domain-specific structured refund proposal (Pydantic validated)."""
    customer_id: str
    transaction_id: str
    amount: Decimal
    currency: Literal["USD"] = "USD"
    reason: str
    evidence_ids: list[str]
    confidence: float = Field(ge=0.0, le=1.0)
    state_version: int = 1


class PolicyDecision(BaseModel):
    """Deterministic verdict produced by the policy engine."""
    decision_id: str
    proposal_id: str
    decision: DecisionType
    policy_name: str
    reason: str
    action_hash: str
    required_approver_role: Optional[str] = None
    evidence_verified: list[str] = Field(default_factory=list)
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)


class ApprovalRequest(BaseModel):
    """Human-in-the-loop review ticket bound to a specific action proposal hash."""
    approval_id: str
    proposal_id: str
    action_hash: str
    workflow_id: str
    run_id: str
    organization_id: str
    agent_id: str
    action: str
    target: str
    summary: str
    reason: str
    evidence_items: list[dict[str, Any]] = Field(default_factory=list)
    risk_tier: RiskTier
    confidence: float
    state_version: int
    status: ApprovalStatus = ApprovalStatus.PENDING
    reviewer_id: Optional[str] = None
    reviewer_comment: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    resolved_at: Optional[datetime] = None
